AWSTemplateFormatVersion: "2010-09-09"
Description: RDS Deletion Protected Stack

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS access SG
      VpcId: 
        Fn::ImportValue: cfn-workshop-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - Fn::ImportValue: cfn-workshop-PublicSubnet1
        - Fn::ImportValue: cfn-workshop-PublicSubnet2

  MyDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBName: testdb
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: Password123!
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  DBName:
    Description: RDS table name
    Value: !Ref MyDB
    Export:
      Name: !Sub "${AWS::StackName}-DBName"
