AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Dashboard (S3 + API Gateway + Lambda + RDS MySQL + CORS)

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of an existing IAM role with Lambda permissions
    Default: arn:aws:iam::763884754454:role/LabRole
  DBPassword:
    Type: String
    NoEcho: true
    Default: #password
  LambdaDeploymentBucket:
    Type: String
    Default: serverless-dashboard-lambda-deploy

Resources:

  ############################
  # VPC
  ############################
  DashboardVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  ############################
  # Private Subnets
  ############################
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DashboardVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DashboardVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false

  ############################
  # Security Groups
  ############################
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda SG
      VpcId: !Ref DashboardVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      VpcId: !Ref DashboardVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref LambdaSG

  ############################
  # RDS Subnet Group
  ############################
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  ############################
  # RDS Instance
  ############################
  DashboardDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: serverless_dashboard
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: #user
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 0

  ############################
  # Frontend S3 Bucket
  ############################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-dashboard-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  ############################
  # Lambda Function
  ############################
  DashboardLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: serverless-dashboard-backend
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 10
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSG
      Environment:
        Variables:
          DB_HOST: !GetAtt DashboardDB.Endpoint.Address
          DB_USER: #user
          DB_PASS: !Ref DBPassword
          DB_NAME: serverless_dashboard
      Code:
        S3Bucket: !Ref LambdaDeploymentBucket
        S3Key: lambda_package1.zip

  ############################
  # API Gateway (GET /status)
  ############################
  DashboardApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: serverless-dashboard-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["GET", "OPTIONS"]
        AllowHeaders: ["*"]

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DashboardApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DashboardLambda.Arn
      PayloadFormatVersion: '2.0'

  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DashboardApi
      RouteKey: GET /status
      Target: !Sub integrations/${LambdaIntegration}

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref DashboardApi
      StageName: $default
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DashboardLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${DashboardApi}/*/*
    ############################
  # Public Subnet for EC2
  ############################
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DashboardVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select [0, !GetAZs ""] 
      MapPublicIpOnLaunch: true

   ############################
  # Public Subnet for EC2
  ############################
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DashboardVPC
      CidrBlock: 10.0.0.0/24   # make sure it doesn't overlap
      AvailabilityZone: !Select [0, !GetAZs ""] 
      MapPublicIpOnLaunch: true

  ############################
  # Associate public subnet with existing route table
  ############################
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: rtb-0a136fd9d2c772e5b  # existing route table

  ############################
  # Add default route to existing IGW
  ############################
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: rtb-0a136fd9d2c772e5b
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: igw-0b8343912831afcd3   # existing IGW

  ############################
  # EC2 Security Group
  ############################
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 SG for SSH and RDS access
      VpcId: !Ref DashboardVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref RDSSG

  ############################
  # EC2 Instance
  ############################
  DashboardEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: muuu
      ImageId: ami-0c398cb65a93047f2
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref EC2SG
      Tags:
        - Key: Name
          Value: DashboardEC2

Outputs:
  FrontendBucketURL:
    Value: !GetAtt FrontendBucket.WebsiteURL

  ApiEndpoint:
    Value: !Sub "${DashboardApi.ApiEndpoint}/status"
  
  EC2PublicIP:
    Description: Public IP of EC2
    Value: !GetAtt DashboardEC2.PublicIp
