AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template for creating an S3 bucket for static website hosting.
Parameters:
  BucketName:
    Description: The name of the S3 bucket to create.
    Type: String
    Default: gio46
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
Outputs:
  BucketName:
    Description: The name of the created S3 bucket.
    Value: !Ref MyS3Bucket
