AWSTemplateFormatVersion: "2010-09-09"
Description: Test template passing all custom cfn-lint rules without hardcoded AZs

Resources:

  # --- EC2 Instance (t2.micro with correct tag) ---
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      Tags:
        - Key: FreeTierEligible
          Value: true
        - Key: Name
          Value: MyInstance

  # --- EC2 Volume (gp3 with correct Priority) ---
  MyVolume:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: gp3
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ""   # dynamically picks the first AZ in the region
      Tags:
        - Key: Priority
          Value: 5000
        - Key: Name
          Value: MyVolume

  # --- S3 Bucket (public access allowed, correct tag) ---
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      Tags:
        - Key: PublicAccessAllowed
          Value: true
        - Key: Name
          Value: MyBucket

  # --- EC2 Instance (m5.large with valid PerformanceCritical) ---
  AnotherInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m5.large
      ImageId: ami-0c55b159cbfafe1f0
      Tags:
        - Key: PerformanceCritical
          Value: true
        - Key: Name
          Value: AnotherInstance
