AWSTemplateFormatVersion: "2010-09-09"

Description: >
  CloudFormation template to create an EC2 instance and an S3 bucket for storing its logs.
  The EC2 instance will have system variables LOG_BUCKET and APP_ENV set dynamically.

Parameters:
  AmiId:
    Description: AMI ID to launch the EC2 instance.
    Type: AWS::EC2::Image::Id

  InstanceType:
    Description: EC2 instance type (e.g., t2.micro, t3.micro, etc.)
    Type: String
    Default: t2.micro

  LogBucketNamePrefix:
    Description: Prefix for the log S3 bucket name.
    Type: String
    Default: myapp-logs
  
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName

  UniqueSuffix:
    Description: A unique identifier to append to the bucket name (e.g., initials or random ID).
    Type: String
    Default: gs2589

  AppEnv:
    Description: Application environment (dev, staging, production)
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

Resources:
  # --- S3 Bucket for Logs ---
  WebServerLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${LogBucketNamePrefix}-my-logs-${UniqueSuffix}"
      AccessControl: Private
      Tags:
        - Key: Environment
          Value: !Ref AppEnv
        - Key: Purpose
          Value: Store EC2 Logs

  # --- EC2 Instance ---
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      Tags:
        - Key: Name
          Value: !Sub "web-server-${AppEnv}"

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          echo "Setting environment variables..."
          echo "export LOG_BUCKET=${WebServerLogBucket}" >> /etc/profile.d/logvars.sh
          echo "export APP_ENV=${AppEnv}" >> /etc/profile.d/logvars.sh
          source /etc/profile.d/logvars.sh
          echo "System variables set: LOG_BUCKET=${WebServerLogBucket}, APP_ENV=${AppEnv}" > /var/log/setup_env.log
          # Optionally, you can redirect system logs to S3 (requires IAM role)
          # aws s3 cp /var/log/setup_env.log s3://${WebServerLogBucket}/ --region ${AWS::Region}

Outputs:
  EC2InstanceId:
    Description: The ID of the created EC2 instance
    Value: !Ref WebServerInstance

  EC2PublicIP:
    Description: The public IP of the EC2 instance
    Value: !GetAtt WebServerInstance.PublicIp

  LogBucketName:
    Description: The name of the S3 bucket where logs are stored
    Value: !Ref WebServerLogBucket
